apiVersion: v1
kind: Pod
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec:
  template: 
    metadata:
      name: myapp-pod
      labels:
       app: myapp
       type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
